/*
*******************************    PROBLEM 11 *********************************
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

#include <stdio.h>
#include <stdlib.h>
#include <math.h>

typedef unsigned long long ULL;

ULL limit = 5;

// return the value of the next triangle number
ULL
triangleNumber(ULL n)
{
    return( (n * ( n + 1 )) / 2);
}

// count the number of divisor
ULL
nbDiv(ULL k)
{
    int count = 1;

    for( int i = 1; i <= k / 2 +1; i++)
        if( k % i == 0)
            count++;

    return count;

}

int main()
{
    ULL n, nb;
    for( n = nb = 1; nbDiv(nb) < limit; n++, nb = triangleNumber(n))
        ;

    printf("The value of the first triangle number to have over %llu divisors is the %llu triangle number: %llu\n", limit,n , nb);
    return 0;
}
